# Dockerfile.airflow
FROM apache/airflow:latest
USER root
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean
USER airflow
RUN pip install apache-airflow-providers-apache-spark
RUN pip install apache-airflow-providers-openlineage
