connector.name=kafka
kafka.nodes=kafka:9092
kafka.table-description-dir=/etc/trino/kafka
kafka.hide-internal-columns=false
kafka.table-description-dir=/etc/trino/kafka
kafka.confluent-schema-registry-url=http://schema-registry:8081
