connector.name=kafka
kafka.nodes=kafka:9092
kafka.default-schema=default
kafka.hide-internal-columns=false
kafka.table-description-supplier=CONFLUENT
kafka.confluent-schema-registry-url=http://schema-registry:8081
kafka.confluent-schema-registry-client-cache-size=1000
kafka.empty-field-strategy=IGNORE
